In [1]:
#%load_ext autotime

In [7]:
import pandas as pd
from TDBU_bootstrap_logreg_diff import TDBU_bootstrap_logreg_diff
L = pd.read_csv('data/ladybug.csv', header=None).values
A = pd.read_csv('data/aphid.csv', header=None).values
D = pd.read_csv('data/day.csv', header=None).values


In [10]:
np.random.seed(1)
%time out = TDBU_bootstrap_logreg_diff(A, L, D, itt = 10000, func = col_shuffle)

CPU times: user 3.5 s, sys: 70.9 ms, total: 3.58 s
Wall time: 1.83 s


In [11]:
out["realTD"]

array([[-0.20857355, -0.22572151, -0.15384557, -0.14773982]])

In [12]:
out["ciTD"]

array([[-0.02899398, -0.04652327, -0.04167144, -0.03433279],
       [-0.00271561, -0.00112447,  0.01909746,  0.06195013],
       [ 0.02586205,  0.0520142 ,  0.09591535,  0.13930702]])

array([[-0.20857355, -0.22572151, -0.15384557, -0.14773982]])

In [ ]:
fig,ax=TDBU_plot(out)

In [ ]:
fig.savefig('fi.tiff',  dpi = 400, linewidth = 2)